openapi: 3.0.3

info:
  title: Airport travellers insights service
  description: Service providing insights on flights and airports
  version: '1.0'

servers:
  - url: ''

tags:
  - name: Travel
    description: Operations to manage travels
  - name: Airport
    description: Operation to retrieve information on airports

paths:
  /trips:
    post:
      summary: Register a trip
      description: |
        Register a new round trip travel from an origin to a destination with the departure and
        return dates.

        Origin and destination are represented by their IATA codes and dates must be in the future.
      operationId: registerTrip
      tags: [ Travel ]
      requestBody:
        description: Trip information
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RegisterTripRequest'
      responses:
        '201':
          description: Trip registration registered
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RegisterTripResponse'
  /trips/{tripId}:
    delete:
      summary: Cancel a trip
      description: |
        Cancel an existing trip
      operationId: cancelTrip
      tags: [ Travel ]
      parameters:
        - in: path
          name: tripId
          schema:
            type: string
            format: uuid
          required: true
          description: UUID of the trip to cancel
      responses:
        '200':
          description: Trip canceled
  /airport-insights:
    post:
      summary: Get airport insights
      description: '*TODO Fill this with description*'
      operationId: getAirportInsights
      tags: [ Airport ]
      requestBody:
        description: Target for insights
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/GetAirportInsightsRequest'
      responses:
        '200':
          description: Airport insights
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetAirportInsightsResponse'

components:
  schemas:
    RegisterTripRequest:
      type: object
      properties:
        originAirportCode:
          $ref: '#/components/schemas/AirportIataCode'
        destinationAirportCode:
          $ref: '#/components/schemas/AirportIataCode'
        departureDate:
          description: Departure date from original airport
          type: string
          format: date
        returnDate:
          description: Return date from the destination airport
          type: string
          format: date
      required:
        - originAirportCode
        - destinationAirportCode
        - departureDate
        - returnDate
    RegisterTripResponse:
      type: object
      properties:
        id:
          description: Unique identifier of registered trip
          type: string
          format: uuid
        originAirportCode:
          $ref: '#/components/schemas/AirportIataCode'
        destinationAirportCode:
          $ref: '#/components/schemas/AirportIataCode'
        departureDate:
          description: Departure date from original airport
          type: string
          format: date
        returnDate:
          description: Return date from the destination airport
          type: string
          format: date
      required:
        - id
        - originAirportCode
        - destinationAirportCode
        - departureDate
        - returnDate
    GetAirportInsightsRequest:
      type: object
      properties:
        airportCode:
          $ref: '#/components/schemas/AirportIataCode'
        date:
          description: Date for insights
          type: string
          format: date
      required:
        - airportCode
        - date
    GetAirportInsightsResponse:
      type: object
      properties:
        airportCode:
          $ref: '#/components/schemas/AirportIataCode'
        date:
          description: Date the insights refer to
          type: string
          format: date
        totalTravellers:
          description: Number of travellers in the airport
          type: integer
          format: int32
          example: 4
        leisurePurposeTravellers:
          description: Number of travellers in the airport that are travelling for leisure
          type: integer
          format: int32
          example: 3
        leisurePurposeProbability:
          description: |
            Probability that the travellers are travelling for leisure.
            It can be omitted if `leisurePurposeTravellers` is zero.
          type: string
          example: '0.5612'
        businessPurposeTravellers:
          description: Number of travellers in the airport that are travelling for business
          type: integer
          format: int32
          example: 1
        businessPurposeProbability:
          description: |
            Probability that the travellers are travelling for business.
            It can be omitted if `businessPurposeTravellers` is zero.
          type: string
          example: '0.4502'
      required:
        - airportCode
        - date
        - leisurePurposeTravellers
        - businessPurposeTravellers
    AirportIataCode:
      description: IATA code
      type: string
      example: "LIN"
